// books.js
// Renders three views inside #app based on location.hash, with NO page reloads:
//   #/                                        -> grid of all books
//   #/<bookKey>                               -> chapter/section accordion for that book
//   #/<bookKey>?open=<chapterKey>.<sectionKey> -> accordion, with that chapter (and section) pre-expanded
//   #/<bookKey>/<problemNumber>                -> a dedicated, standalone problem page
//                                                  (own screen, not appended under the accordion), with prev/next
//
// Data comes from booksData.js (generated by generate-books-data.js), which
// stores each problem's full statement HTML directly (so it can be read
// inline while browsing) but NOT its hint/solution — those are fetched
// lazily from ../daily-problems/data/<topic>.json, the same files
// problem-loader.js already uses, only when someone opens the problem page.

(function () {
    const APP = document.getElementById('app');
    const DATA_BASE = '../daily-problems/data/';
    const BOOKS_DATA_BASE = 'data/'; // dedicated per-book problem files, see generate-books-data.js
    const LAST_FOLDER_DATE = '2025-12-31'; // must match problem-loader.js

    const fileCache = {}; // `${source}:${slug}` -> parsed JSON (cached across views)

    // ---------- helpers ----------

    function buildDateURL(dateString) {
        return dateString <= LAST_FOLDER_DATE
            ? `/miscellaneous/daily-problems/${dateString}/`
            : `/miscellaneous/daily-problems/problem/?date=${dateString}`;
    }

    // entry.source is 'daily' (fetch from ../daily-problems/data/) or 'book'
    // (fetch from ./data/) — both file shapes are identical (date, title,
    // difficulty, problem, hint, solution, tags), so this one function and a
    // plain find-by-date works for either.
    async function fetchProblemFile(source, slug) {
        const cacheKey = `${source}:${slug}`;
        if (fileCache[cacheKey]) return fileCache[cacheKey];
        const base = source === 'book' ? BOOKS_DATA_BASE : DATA_BASE;
        const res = await fetch(`${base}${slug}.json`);
        if (!res.ok) throw new Error(`Failed to load ${slug}.json (${res.status})`);
        const data = await res.json();
        fileCache[cacheKey] = data;
        return data;
    }

    // Pulls the exercise number out of a tag like "abstract-algebra-herstein
    // (1.3.2)" or the legacy "Real-Analysis-Rudin-3.11" style — mirrors the
    // parsing generate-books-data.js does server-side, simplified since we
    // don't need to resolve which book a tag belongs to here (we've already
    // fetched the right file for the right book).
    function extractTagNumber(tag) {
        let m = tag.match(/^(.*?)\s*\(([\d]+(?:\.\d+)*)\)$/);
        if (m) return m[2];
        m = tag.match(/^Real-Analysis-Rudin-([\d]+(?:\.\d+)*)$/i);
        if (m) return m[1];
        return null;
    }

    // Date isn't guaranteed unique — book-native entries can leave it empty
    // (they don't need a calendar date), so several problems in the same
    // file could all have date: "". Try matching by date first (fast, and
    // always safe for daily-tagged problems, which always have a real
    // date); if that's empty/ambiguous, fall back to matching by the
    // exercise number embedded in each problem's own tags, which is what's
    // actually guaranteed unique within a book.
    function findProblemInFile(sourceData, entry) {
        const problems = sourceData.problems || [];
        if (entry.date) {
            const byDate = problems.find(p => p.date === entry.date);
            if (byDate) return byDate;
        }
        return problems.find(p => (p.tags || []).some(tag => extractTagNumber(tag) === entry.number));
    }

    function numericSort(keys) {
        return [...keys].sort((a, b) => Number(a) - Number(b));
    }

    function compareDotted(a, b) {
        const pa = a.split('.').map(Number), pb = b.split('.').map(Number);
        for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
            const x = pa[i] || 0, y = pb[i] || 0;
            if (x !== y) return x - y;
        }
        return 0;
    }

    // All problems in a chapter (its own direct problems + everything inside
    // its sections), sorted together by full dotted number.
    function chapterProblemsFlat(chapterNode) {
        const list = [...chapterNode.problems.map(p => ({ ...p, sectionKey: null }))];
        numericSort(Object.keys(chapterNode.sections)).forEach(secKey => {
            chapterNode.sections[secKey].problems.forEach(p => list.push({ ...p, sectionKey: secKey }));
        });
        return list.sort((a, b) => compareDotted(a.number, b.number));
    }

    // Every problem in the whole book, in reading order (chapter, then section, then number).
    function flatProblemList(book) {
        const list = [];
        numericSort(Object.keys(book.chapters)).forEach(chKey => {
            chapterProblemsFlat(book.chapters[chKey]).forEach(p => list.push({ ...p, chapterKey: chKey }));
        });
        return list;
    }

    function difficultyBadge(difficulty) {
        const colors = {
            easy: 'bg-green-100 text-green-800 border-green-300',
            medium: 'bg-yellow-100 text-yellow-800 border-yellow-300',
            hard: 'bg-red-100 text-red-800 border-red-300'
        };
        const c = colors[(difficulty || '').toLowerCase()] || colors.medium;
        return difficulty ? `<span class="inline-block ${c} text-xs font-semibold rounded px-2 py-0.5 border">${difficulty}</span>` : '';
    }

    // Retries for a couple of seconds in case the MathJax script hasn't
    // finished loading/initializing yet (it's loaded with `async`).
    function typesetMath(el, retriesLeft) {
        if (retriesLeft === undefined) retriesLeft = 20;
        if (window.MathJax && window.MathJax.typesetPromise) {
            window.MathJax.typesetPromise([el]).catch(err => console.log('MathJax render error:', err));
        } else if (retriesLeft > 0) {
            setTimeout(() => typesetMath(el, retriesLeft - 1), 150);
        } else {
            console.warn('MathJax never became available; math on this page will show as raw LaTeX.');
        }
    }

    function accentClasses(color) {
        // color is a plain Tailwind color name, e.g. "rose", "sky", "emerald"...
        return {
            chip: `bg-${color}-50 text-${color}-700 border-${color}-200`,
            bar: `bg-${color}-400`,
            text: `text-${color}-600`,
            hoverBg: `hover:bg-${color}-50`,
            ring: `ring-${color}-100`,
        };
    }

    // A title that's really just a restatement of the problem text (common
    // when a problem's title and body were both hand-typed from the same
    // exercise) shouldn't be shown twice — strip tags/whitespace/trailing
    // punctuation from both and compare.
    function stripHtml(html) {
        const tmp = document.createElement('div');
        tmp.innerHTML = html || '';
        return (tmp.textContent || '').trim();
    }
    function normalizeForCompare(s) {
        return s.replace(/\s+/g, ' ').trim().replace(/[.\s]+$/, '').toLowerCase();
    }
    function isRedundantTitle(title, problemHtml) {
        if (!title) return true;
        const t = normalizeForCompare(title);
        const p = normalizeForCompare(stripHtml(problemHtml));
        if (!t || !p) return false;
        return t === p || p.startsWith(t) || t.startsWith(p);
    }

    // Some problem statements contain their own embedded <a> link (e.g. "see
    // the previous problem"). That's fine standalone, but a chapter/section
    // listing row is itself already one big <a> wrapping the whole card — an
    // <a> nested inside an <a> is invalid HTML and browsers respond by
    // silently closing the outer link early, which breaks the row's layout
    // (shows up as odd extra spacing). So inside listing rows specifically,
    // any embedded links get flattened to plain text before rendering.
    function neutralizeNestedLinks(html) {
        const tmp = document.createElement('div');
        tmp.innerHTML = html || '';
        tmp.querySelectorAll('a').forEach(a => {
            const span = document.createElement('span');
            span.className = 'text-gray-700';
            span.innerHTML = a.innerHTML;
            a.replaceWith(span);
        });
        return tmp.innerHTML;
    }

    // Titles are typically written as "<Author name(s)> - <number> - <description>"
    // or "<Author name(s)> <number>: <description>". Rather than needing an
    // exact per-book name to match against (which breaks the moment an author
    // is phrased differently than expected — e.g. "Hoffman" vs "Hoffman and
    // Kunze"), this strips *any* short leading segment before the first "-"
    // or ":" (plus an optional number+separator right after it). It's bounded
    // to the first 40 characters, and refuses to cross a "$", so it can never
    // eat into the actual mathematical content of a title that has no author
    // prefix at all (math-heavy titles almost always start with "$" early on).
    function stripBookPrefix(title) {
        if (!title) return title;
        const re = /^\s*[^$\n]{1,40}?[-:]\s*(?:[\d.]+\s*[-:]\s*)?/;
        const m = title.match(re);
        if (!m) return title;
        const stripped = title.slice(m[0].length).trim();
        return stripped || title; // never return an empty title
    }

    // ---------- view: book grid ----------

    function renderBookGrid() {
        document.getElementById('page-title').textContent = 'Book Solutions - Sachchidanand Prasad';
        window.scrollTo({ top: 0 });

        if (typeof booksData === 'undefined' || Object.keys(booksData).length === 0) {
            APP.innerHTML = `<p class="text-center text-gray-500 py-20">No book-tagged problems found yet.</p>`;
            return;
        }

        const cards = Object.entries(booksData).map(([key, book]) => {
            let chapterCount = Object.keys(book.chapters).length;
            let problemCount = 0;
            Object.values(book.chapters).forEach(ch => { problemCount += chapterProblemsFlat(ch).length; });
            const a = accentClasses(book.color);

            // The accent color always renders as the base layer of the cover
            // box. If a cover image is available it sits on top, filling the
            // box — if it fails to load for any reason, onerror just hides
            // the <img>, so the colored placeholder shows through underneath
            // with zero extra fallback logic needed.
            const coverBox = `
                <div class="flex-shrink-0 w-14 h-20 rounded-md overflow-hidden border border-gray-200 relative ${a.bar}">
                    ${book.cover ? `<img src="${book.cover}" alt="${book.title} cover" loading="lazy"
                          class="absolute inset-0 w-full h-full object-cover"
                          onerror="this.style.display='none';">` : ''}
                </div>`;

            return `
                <a href="#/${encodeURIComponent(key)}"
                   class="group flex gap-4 rounded-2xl border border-gray-200 bg-white p-4 transition-all duration-200 hover:border-gray-300 hover:shadow-md">
                    ${coverBox}
                    <div class="flex-1 min-w-0">
                        <h3 class="text-lg font-semibold text-gray-900 leading-snug group-hover:text-gray-700">${book.title}</h3>
                        <p class="text-sm text-gray-500 mt-1">${book.author}</p>
                        <p class="text-xs text-gray-400 mt-3">${chapterCount} chapter${chapterCount === 1 ? '' : 's'} &middot; ${problemCount} problem${problemCount === 1 ? '' : 's'}</p>
                    </div>
                </a>`;
        }).join('');

        APP.innerHTML = `
            <div class="mb-10">
                <h2 class="text-3xl font-semibold text-gray-900 tracking-tight">Book Solutions</h2>
                <p class="text-gray-500 mt-2 max-w-xl">Every daily problem sourced from a textbook, organized by book, chapter and section.</p>
            </div>
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                ${cards}
            </div>`;
    }

    // ---------- view: chapter / section accordion (browsing only — no hint/solution here) ----------

    function renderBookView(bookKey, openSpec) {
        const book = booksData[bookKey];
        if (!book) { window.location.hash = '#/'; return; }

        document.getElementById('page-title').textContent = `${book.title} Solutions - Sachchidanand Prasad`;
        window.scrollTo({ top: 0 });

        const a = accentClasses(book.color);
        const chapterKeys = numericSort(Object.keys(book.chapters));

        // openSpec looks like "2" or "2.3" (chapter, or chapter.section)
        let [openChapter, openSection] = (openSpec || '').split('.');
        if (!openChapter || !book.chapters[openChapter]) openChapter = chapterKeys[0];

        function problemRow(p) {
            const cleanTitle = stripBookPrefix(p.title);
            const showTitle = cleanTitle && !isRedundantTitle(cleanTitle, p.problem);
            return `
                <a href="#/${encodeURIComponent(bookKey)}/${encodeURIComponent(p.number)}"
                   class="block px-4 py-4 -mx-1 border-b border-gray-100 last:border-b-0 even:bg-gray-50/60 transition-colors hover:bg-gray-100">
                    <div class="flex items-center gap-2 mb-1.5">
                        <span class="coord ${a.text}">${p.number}</span>
                        ${difficultyBadge(p.difficulty)}
                    </div>
                    ${showTitle ? `<p class="text-xs uppercase tracking-wide text-gray-400 font-medium mb-1.5">${cleanTitle}</p>` : ''}
                    <div class="problem-preview text-[15px] text-gray-800 leading-relaxed">${neutralizeNestedLinks(p.problem)}</div>
                </a>`;
        }

        function sectionBlock(chKey, secKey, secNode) {
            const isOpen = chKey === openChapter && secKey === openSection;
            const problems = [...secNode.problems].sort((x, y) => compareDotted(x.number, y.number));
            return `
                <div class="ml-2 border-l-2 border-gray-100 pl-4 mt-2">
                    <button type="button" class="section-toggle w-full flex items-center justify-between py-2 border-b border-gray-100 text-left"
                            data-chapter="${chKey}" data-section="${secKey}">
                        <span class="text-sm font-semibold text-gray-600">Section ${chKey}.${secKey}</span>
                        <span class="flex items-center gap-2 text-xs text-gray-400">
                            ${problems.length} problem${problems.length === 1 ? '' : 's'}
                            <svg class="chevron w-3.5 h-3.5 transition-transform ${isOpen ? 'rotate-180' : ''}" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
                        </span>
                    </button>
                    <div class="section-panel ${isOpen ? '' : 'hidden'} pb-2" data-panel-chapter="${chKey}" data-panel-section="${secKey}">
                        ${problems.map(problemRow).join('')}
                    </div>
                </div>`;
        }

        const chaptersHtml = chapterKeys.map(chKey => {
            const chNode = book.chapters[chKey];
            const isOpen = chKey === openChapter;
            const directProblems = [...chNode.problems].sort((x, y) => compareDotted(x.number, y.number));
            const sectionKeys = numericSort(Object.keys(chNode.sections));
            const total = chapterProblemsFlat(chNode).length;

            return `
                <div class="border border-gray-200 rounded-2xl mb-3 overflow-hidden bg-white">
                    <button type="button"
                            class="chapter-toggle w-full flex items-center justify-between px-5 py-4 border-b border-gray-100 hover:bg-gray-50 text-left"
                            data-chapter="${chKey}">
                        <span class="font-semibold text-gray-900">Chapter ${chKey}</span>
                        <span class="flex items-center gap-3 text-sm text-gray-400">
                            ${total} problem${total === 1 ? '' : 's'}
                            <svg class="chevron w-4 h-4 transition-transform ${isOpen ? 'rotate-180' : ''}" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
                        </span>
                    </button>
                    <div class="chapter-panel ${isOpen ? '' : 'hidden'} px-5 pb-4" data-panel="${chKey}">
                        ${directProblems.length ? `<div>${directProblems.map(problemRow).join('')}</div>` : ''}
                        ${sectionKeys.map(secKey => sectionBlock(chKey, secKey, chNode.sections[secKey])).join('')}
                    </div>
                </div>`;
        }).join('');

        APP.innerHTML = `
            <a href="#/" class="text-sm text-gray-500 hover:text-gray-700">&larr; All books</a>
            <div class="flex items-center gap-4 mt-4 mb-8">
                <div class="h-10 w-1.5 rounded-full ${a.bar}"></div>
                <div>
                    <h2 class="text-2xl font-semibold text-gray-900 tracking-tight">${book.title}</h2>
                    <p class="text-gray-500 text-sm">${book.author}</p>
                </div>
            </div>
            <div id="chapters-container">${chaptersHtml}</div>`;

        APP.querySelectorAll('.chapter-toggle').forEach(btn => {
            btn.addEventListener('click', () => {
                const key = btn.dataset.chapter;
                const panel = APP.querySelector(`[data-panel="${CSS.escape(key)}"]`);
                const chevron = btn.querySelector('.chevron');
                panel.classList.toggle('hidden');
                chevron.classList.toggle('rotate-180');
            });
        });
        APP.querySelectorAll('.section-toggle').forEach(btn => {
            btn.addEventListener('click', (e) => {
                e.stopPropagation();
                const ch = btn.dataset.chapter, sec = btn.dataset.section;
                const panel = APP.querySelector(`[data-panel-chapter="${CSS.escape(ch)}"][data-panel-section="${CSS.escape(sec)}"]`);
                const chevron = btn.querySelector('.chevron');
                panel.classList.toggle('hidden');
                chevron.classList.toggle('rotate-180');
            });
        });

        typesetMath(APP);
    }

    // ---------- view: standalone problem page ----------

    async function renderProblemPage(bookKey, problemNumber) {
        const book = booksData[bookKey];
        if (!book) { window.location.hash = '#/'; return; }

        const flat = flatProblemList(book);
        const idx = flat.findIndex(p => p.number === problemNumber);
        if (idx === -1) {
            APP.innerHTML = `<p class="text-red-600">Problem ${problemNumber} not found in "${book.title}".</p>
                <a href="#/${encodeURIComponent(bookKey)}" class="text-gray-600 hover:text-gray-800 text-sm">&larr; Back to ${book.title}</a>`;
            return;
        }
        const entry = flat[idx];
        const prevEntry = flat[idx - 1];
        const nextEntry = flat[idx + 1];
        const chapterFlat = chapterProblemsFlat(book.chapters[entry.chapterKey]);
        const posInChapter = chapterFlat.findIndex(p => p.number === entry.number) + 1;
        const openSpec = entry.sectionKey ? `${entry.chapterKey}.${entry.sectionKey}` : entry.chapterKey;
        const locationLabel = entry.sectionKey ? `Section ${entry.chapterKey}.${entry.sectionKey}` : `Chapter ${entry.chapterKey}`;
        const a = accentClasses(book.color);

        document.getElementById('page-title').textContent = `${entry.title} - ${book.title} - Sachchidanand Prasad`;
        window.scrollTo({ top: 0 });

        function pagerButton(target, direction) {
            if (!target) return `<span class="flex-1"></span>`;
            const arrow = direction === 'prev' ? '&larr;' : '&rarr;';
            const content = direction === 'prev'
                ? `${arrow} <span class="hidden sm:inline">Problem</span> ${target.number}`
                : `<span class="hidden sm:inline">Problem</span> ${target.number} ${arrow}`;
            return `<a href="#/${encodeURIComponent(bookKey)}/${encodeURIComponent(target.number)}"
                       class="flex-1 ${direction === 'next' ? 'text-right' : ''} text-sm font-medium ${a.text} px-4 py-2.5 rounded-xl ${a.hoverBg} transition-all">
                       ${content}
                    </a>`;
        }

        const pagerHtml = `
            <div class="flex items-center justify-between border border-gray-200 rounded-xl bg-white">
                ${pagerButton(prevEntry, 'prev')}
                <span class="text-xs text-gray-400 px-2 whitespace-nowrap">${posInChapter} of ${chapterFlat.length} &middot; ${locationLabel}</span>
                ${pagerButton(nextEntry, 'next')}
            </div>`;

        APP.innerHTML = `
            <div class="flex items-center gap-2 text-sm text-gray-500 mb-4 flex-wrap">
                <a href="#/" class="hover:text-gray-800">All books</a>
                <span class="text-gray-300">/</span>
                <a href="#/${encodeURIComponent(bookKey)}?open=${encodeURIComponent(openSpec)}" class="hover:text-gray-800">${book.title}</a>
                <span class="text-gray-300">/</span>
                <span class="text-gray-400">${locationLabel}</span>
            </div>

            ${pagerHtml}

            <div id="problem-content" class="border border-gray-200 rounded-2xl p-6 sm:p-8 bg-white mt-4">
                <div class="text-center py-16 text-gray-400">Loading problem ${problemNumber}&hellip;</div>
            </div>

            <div class="mt-4">${pagerHtml}</div>

            <div class="text-center mt-6">
                <a href="#/${encodeURIComponent(bookKey)}?open=${encodeURIComponent(openSpec)}" class="text-sm text-gray-500 hover:text-gray-700">
                    &larr; Back to ${locationLabel}
                </a>
            </div>`;

        const content = document.getElementById('problem-content');

        let sourceData;
        try {
            sourceData = await fetchProblemFile(entry.source, entry.topic);
        } catch (e) {
            content.innerHTML = `<p class="text-red-600">Could not load this problem (${e.message}).</p>`;
            return;
        }
        if (document.getElementById('problem-content') !== content) return; // navigated away while loading
        const problem = findProblemInFile(sourceData, entry);
        if (!problem) {
            content.innerHTML = `<p class="text-red-600">Problem data missing for ${entry.number}.</p>`;
            return;
        }

        const hasHint = problem.hint && problem.hint.trim() !== '';
        const hasSolution = problem.solution && problem.solution.trim() !== '';
        const cleanTitle = stripBookPrefix(problem.title);
        const showTitle = cleanTitle && !isRedundantTitle(cleanTitle, problem.problem);

        content.innerHTML = `
            <div class="flex items-center justify-between flex-wrap gap-2 mb-3">
                <div class="flex items-center gap-2">
                    <span class="text-sm text-gray-500">Problem</span>
                    <span class="coord ${a.text}">${entry.number}</span>
                    ${difficultyBadge(problem.difficulty)}
                </div>
                ${entry.source === 'daily' ? `<a href="${buildDateURL(entry.date)}" target="_blank"
                   class="text-xs text-gray-400 hover:text-gray-600">Permalink (${entry.date}) &#8599;</a>` : ''}
            </div>
            ${showTitle ? `
            <p class="text-xs uppercase tracking-wide text-gray-400 font-medium mb-1">${cleanTitle}</p>
            <hr class="border-gray-100 mb-4">` : ''}
            <div class="text-lg leading-relaxed text-gray-900 ${showTitle ? '' : 'mt-1'}">
                ${problem.problem}
            </div>

            <div class="mt-6 flex flex-wrap items-center gap-2">
                ${hasHint ? `<button id="pp-hint-btn" class="bg-yellow-500 text-white px-4 py-1.5 rounded hover:bg-yellow-600 text-sm font-medium">Show Hint</button>` : ''}
                ${hasSolution ? `<button id="pp-sol-btn" class="bg-green-500 text-white px-4 py-1.5 rounded hover:bg-green-600 text-sm font-medium">Show Solution</button>` : ''}
            </div>

            ${hasHint ? `
            <div id="pp-hint-box" class="hidden border-l-4 border-yellow-500 mt-4 p-4 bg-yellow-50 rounded-r-lg">
                <div class="leading-relaxed lg:text-lg md:text-base text-justify"><strong>Hint:</strong> ${problem.hint}</div>
            </div>` : ''}

            ${hasSolution ? `
            <div id="pp-sol-box" class="hidden border-l-4 border-green-500 mt-4 p-4 bg-green-50 rounded-r-lg">
                <div class="leading-relaxed lg:text-lg md:text-base text-justify"><strong>Solution:</strong> ${problem.solution}</div>
            </div>` : ''}`;

        const hintBtn = document.getElementById('pp-hint-btn');
        const hintBox = document.getElementById('pp-hint-box');
        if (hintBtn) hintBtn.addEventListener('click', () => {
            hintBox.classList.toggle('hidden');
            hintBtn.textContent = hintBox.classList.contains('hidden') ? 'Show Hint' : 'Hide Hint';
            if (!hintBox.classList.contains('hidden')) typesetMath(hintBox);
        });

        const solBtn = document.getElementById('pp-sol-btn');
        const solBox = document.getElementById('pp-sol-box');
        if (solBtn) solBtn.addEventListener('click', () => {
            solBox.classList.toggle('hidden');
            solBtn.textContent = solBox.classList.contains('hidden') ? 'Show Solution' : 'Hide Solution';
            if (!solBox.classList.contains('hidden')) typesetMath(solBox);
        });

        typesetMath(content);
    }

    // ---------- router ----------

    function route() {
        const raw = window.location.hash.replace(/^#\/?/, ''); // strip leading '#' or '#/'
        if (!raw) { renderBookGrid(); return; }

        if (raw.includes('/')) {
            const slashIdx = raw.indexOf('/');
            const bookKey = decodeURIComponent(raw.slice(0, slashIdx));
            const problemNumber = decodeURIComponent(raw.slice(slashIdx + 1));
            renderProblemPage(bookKey, problemNumber);
        } else if (raw.includes('?')) {
            const [bookKeyPart, query] = raw.split('?');
            const params = new URLSearchParams(query);
            renderBookView(decodeURIComponent(bookKeyPart), params.get('open'));
        } else {
            renderBookView(decodeURIComponent(raw), null);
        }
    }

    window.addEventListener('hashchange', route);
    document.addEventListener('DOMContentLoaded', route);
})();